# Generated by Django 3.2.3 on 2021-05-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0005_auto_20210520_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
