# Generated by Django 3.2.3 on 2021-05-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0017_auto_20210522_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(),
        ),
    ]
