# Generated by Django 3.2.3 on 2021-05-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0029_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='posts', to='Insta.Profile'),
        ),
    ]
